//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace URC_Server.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("URC_Server.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aceptar.
        /// </summary>
        public static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desconectar.
        /// </summary>
        public static string conexion_btn_disconnect {
            get {
                return ResourceManager.GetString("conexion_btn_disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lea el código QR con su aplicación móvil para conectar de forma automática. En caso de error en la conexión pruebe a realizar los ajustes manualmente..
        /// </summary>
        public static string conexion_helpText {
            get {
                return ResourceManager.GetString("conexion_helpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Conexiones.
        /// </summary>
        public static string conexion_title {
            get {
                return ResourceManager.GetString("conexion_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asignar.
        /// </summary>
        public static string controls_btn_assign {
            get {
                return ResourceManager.GetString("controls_btn_assign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Presiona una tecla para asignar....
        /// </summary>
        public static string dialog_assign_text {
            get {
                return ResourceManager.GetString("dialog_assign_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asignar....
        /// </summary>
        public static string dialog_assign_title {
            get {
                return ResourceManager.GetString("dialog_assign_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Desea borrar el grupo.
        /// </summary>
        public static string dialog_deleteGroups_text {
            get {
                return ResourceManager.GetString("dialog_deleteGroups_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo grupo.
        /// </summary>
        public static string dialog_newGroups_hint {
            get {
                return ResourceManager.GetString("dialog_newGroups_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre del grupo.
        /// </summary>
        public static string dialog_newGroups_text {
            get {
                return ResourceManager.GetString("dialog_newGroups_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo grupo.
        /// </summary>
        public static string dialog_newGroups_title {
            get {
                return ResourceManager.GetString("dialog_newGroups_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Inicio&gt;
        ///  &lt;Group name=&quot;Connection&quot;&gt;
        ///    &lt;Item name=&quot;Connect device&quot;&gt;
        ///      &lt;Image src=&quot;conexion_dispositivo_01.png&quot;&gt;Make sure the two devices are on the same network.&lt;/Image&gt;
        ///      &lt;Image src=&quot;conexion_dispositivo_02.png&quot;&gt;QR Reader.&lt;/Image&gt;
        ///      &lt;Image src=&quot;conexion_dispositivo_03.png&quot;&gt;Manual way.&lt;/Image&gt;
        ///      &lt;Image src=&quot;conexion_dispositivo_04.png&quot;&gt;Device connected !&lt;/Image&gt;
        ///    &lt;/Item&gt;
        ///  &lt;/Group&gt;
        ///
        ///  &lt;Group name=&quot;Controls&quot;&gt;
        ///    &lt;Item name=&quot;Buttons: Ne [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string English_inicio {
            get {
                return ResourceManager.GetString("English_inicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Inicio&gt;
        ///  &lt;Group name=&quot;Conexión&quot;&gt;
        ///    &lt;Item name=&quot;Conectar dispositivo&quot;&gt;
        ///      &lt;Image src=&quot;conexion_dispositivo_01.png&quot;&gt;Asegúrese de que los dos dispositivos estén en la misma red.&lt;/Image&gt;
        ///      &lt;Image src=&quot;conexion_dispositivo_02.png&quot;&gt;Lector de QR.&lt;/Image&gt;
        ///      &lt;Image src=&quot;conexion_dispositivo_03.png&quot;&gt;Forma manual.&lt;/Image&gt;
        ///      &lt;Image src=&quot;conexion_dispositivo_04.png&quot;&gt;¡ Dispositivo conectado !&lt;/Image&gt;
        ///    &lt;/Item&gt;
        ///  &lt;/Group&gt;
        ///
        ///  &lt;Group name=&quot;Mando&quot;&gt;
        ///     [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string Español_inicio {
            get {
                return ResourceManager.GetString("Español_inicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ajustes.
        /// </summary>
        public static string settings_adjust {
            get {
                return ResourceManager.GetString("settings_adjust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Preguntar antes de conectar:.
        /// </summary>
        public static string settings_askBeforeConnect {
            get {
                return ResourceManager.GetString("settings_askBeforeConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Idioma:.
        /// </summary>
        public static string settings_languages {
            get {
                return ResourceManager.GetString("settings_languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Conexiones máximas:.
        /// </summary>
        public static string settings_maxConnections {
            get {
                return ResourceManager.GetString("settings_maxConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Conexión.
        /// </summary>
        public static string TAB_conexion {
            get {
                return ResourceManager.GetString("TAB_conexion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configuración.
        /// </summary>
        public static string TAB_config {
            get {
                return ResourceManager.GetString("TAB_config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mandos.
        /// </summary>
        public static string TAB_control {
            get {
                return ResourceManager.GetString("TAB_control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicio.
        /// </summary>
        public static string TAB_index {
            get {
                return ResourceManager.GetString("TAB_index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Si.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
